### ISSUE TITLE
Running the intrinsic calibration

### ISSUE THREAD

**Issue by lambozan** [idiap/multicamera-calibration#5]
Thanks for the uploading of this useful code. While something goes wrong when I run the intrinsic calibration. My command is:
bin/intrinsic -p chessboard -n 15 -W 25 -H 25 /home/usr1/CalibImg/ImageChessBoard4/left/\*.bmp /home/usr1/CalibImg/ImageChessBoard4/left/intrinsic.json
Then the terminal shows:
Traceback (most recent call last):
  File "bin/intrinsic", line 178, in <module>
    main()
  File "bin/intrinsic", line 128, in main
    selected_indices = select_images(image_points, opts.num)
  File "bin/intrinsic", line 104, in select_images
    imgpoint = image_points[imlist[-1]]
IndexError: list index out of range
Could I ask how to fix it?

**Comment by SalimKayal** [comment]
Is the path correct ? this would happen if imlist is empty. Have you escaped the wildcard ?

**Comment by dongshengLiu** [comment]
I get the same problem

**Comment by SalimKayal** [comment]
How many calibration images do you have ?

**Comment by dongshengLiu** [comment]
> How many calibration images do you have ?

Thank you for your reply, I used 10 pictures to calibrate the intrinsic matrix.

**Comment by SalimKayal** [comment]
if you use --num=10 or less does it still happen ?

**Comment by dongshengLiu** [comment]
> if you use --num=10 or less does it still happen

I use command like the style 
 "bin/intrinsic -o /home/user1/frames_with_grid -s /home/user1/camera1/selected_frames_with_grid home/user1/camera1/frames/\*.bmp /home/user1/camera1/intrinsic.json",
the above problem occurred.

Then I use command like the style 
"./bin/intrinsic --num 10 --width 6 --height 9 --pattern chessboard --full_output /home/lds/workspace/multicamera-calibration/data/frames_with_grid --select_output /home/lds/workspace/multicamera-calibration/data/selected_frames_with_grid /home/lds/workspace/multicamera-calibration/data/MySet/*.png /home/lds/workspace/multicamera-calibration/data/intrinsic.json"
there is such a problem
"intrinsic: error: unrecognized arguments: /home/lds/workspace/multicamera-calibration/data/MySet/left03.png /home/lds/workspace/multicamera-calibration/data/MySet/left04.png /home/lds/workspace/multicamera-calibration/data/MySet/left05.png /home/lds/workspace/multicamera-calibration/data/MySet/left06.png /home/lds/workspace/multicamera-calibration/data/MySet/left07.png /home/lds/workspace/multicamera-calibration/data/MySet/left08.png /home/lds/workspace/multicamera-calibration/data/MySet/left09.png /home/lds/workspace/multicamera-calibration/data/MySet/left10.png /home/lds/workspace/multicamera-calibration/data/intrinsic.json"

**Comment by SalimKayal** [comment]
you forgot to escape the wildcard. it got expanded by your shell instead of the script
